### ISSUE TITLE
[Build] yarn build {package_name}

### ISSUE THREAD

**Issue by skoging** [ojkelly/yarn.build#144]
Specify root package(s) to build in a similar manner to how other Yarn workspace commands do it: `yarn workspaces foreach --recursive --from=@scope/* run build` or `yarn workspace @scope/name run build`.

Glob patterns should be supported.

Ideally the support for using project name as positional parameter like the path is now, but I understand if this might be too risky.

We're curently using a package.json script to achieve something similar with yarn workspaces foreach:
`"build": "yarn workspaces foreach -vip --topological-dev --recursive --from=$0"`  
I'd like to be able to start using this tool without changing any of our current processes, but with this plugin there does not seem to be a way to customize the `yarn build` command anymore. If there was, then having the package name be a named parameter would not be a big deal, as I could achieve what I want the same way I've done before.

**Comment by ojkelly** [comment]
Yeah this would be a nice addition.

Currently it's all path based, the code for it starts here https://github.com/ojkelly/yarn.build/blob/main/packages/plugins/plugin-build/src/commands/build/index.ts#L105

So we'd really just need a way to understand the difference between a path and a package scope.

Yarn.build does also have build caching, so reruns are very cheap. What is the value to you in being able to build `@scope/*` instead of by path, or just eveyrthing, and then only what's changed?

--

> I'd like to be able to start using this tool without changing any of our current processes, but with this plugin there does not seem to be a way to customize the yarn build command anymore. 

You can run `yarn build -c customScriptName` where `customScriptName` is a key in `package.json#scripts`. and it will run that command in every workspace.

`yarn test` is really just `yarn build -c test`

In some projects I have `yarn build -c upload` to upload any build artefacts.

They will be run in topological order so in some cases `foreach` might be quicker if they don't depend on each other.

Note that yarn.build is designed to be as fast and parallel as possible. So you should only run one instance of it on a codebase at a time.

Additionally `yarn workspaces foreach run build` will run the build script bypassing the plugin, which is useful when you need to run the build/test scripts in certain situations.
