### ISSUE TITLE
Error for circular dependency is not clear

### ISSUE THREAD

**Issue by ojkelly** [ojkelly/yarn.build#195]
When a circular dependency occurs the call stack blows up, and provides no meaningful error.

Need a way to short-circuit the loop, fail, and provide fix instructions.

**Comment by lodmfjord** [comment]
I created a small debug util that I use to spot the error, I used a lot simpler way to create the graph — but it might be a way that is not suitable for yarn.build. 

I am gonna push it on git later today and share it with you.

**Comment by lodmfjord** [comment]
https://github.com/lodmfjord/yarn.build.debug

![image](https://user-images.githubusercontent.com/5091589/161246423-ebc5064d-0be1-4613-bf51-d6055b63e725.png)

(the UI is quite similar to the build query … but this is a lot smaller code and just for debugging at the moment :)

I am not sure if this solution might be helpful. I just got fed up with programmers at my work, spending hours getting stuck on circ. dep. This solution has already saved time even though it is just a hack.

Instead of travelling every package and then recursively following every deps, I only visit every package in the project once. Thus I do not have loop problems but enough information to create a dependency tree.

This solution seems too simple, so I guess it might not be perfect, but I am just putting this here to start a discussion.

The drawback I see right away is that in a big project, graph-class visits every package, even when only building a small package, but the graph could be cached in the future (?).

**Comment by ojkelly** [comment]
If we can catch or deliberately check for a circular dependency, and then show a visual of what is causing it, that would go a long way to solving this.

> The drawback I see right away is that in a big project, graph-class visits every package, even when only building a small package, but the graph could be cached in the future (?).

I think the issue probably is somewhere in the code this is happening, but not catching the circular dependency. I'm certain there's some optimisation's that can be done to the traversal algo. There's likely plenty of prior art on this I need to dig into.

**Comment by lodmfjord** [comment]
Ahh you made me and my team happy @ojkelly.

Thanks again!
