### ISSUE TITLE
Support targetted builds

### ISSUE THREAD

**Issue by oliversalzburg** [ojkelly/yarn.build#32]
A problem I'm often running into with yarn.build is builds I don't care about in the current debug cycle.

I have a workspace with a few core dependencies and then several, much larger applications that consume them. I usually focus work on one of the larger applications.  
When I make changes to a core library, it causes the entire workspace, with all large applications, to be rebuilt, as they depend on the changed core module.

It would be really useful to tell yarn.build that I want to target a specific workspace and have only that workspace and its dependencies built as needed.

This would allow to construct highly optimized build workflows for local development.

**Comment by ojkelly** [comment]
I think this is something you can do by running yarn.build in the specific directory you want.

However, I agree it would be really nice to expand this functionality out to something like `yarn build packages/backend/*`.

Currently I believe the process is:

Am I in a package?
 - yes: built it and its deps
 - no: built everything


I think is all stems from here https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/build/index.ts#L82

```
        const { project, workspace: cwdWorkspace } = await Project.find(
          configuration,
          this.context.cwd
        );

        const targetWorkspace = cwdWorkspace || project.topLevelWorkspace;
```

So we can probably just add either a positional arg or flag for the package glob to build, and check for that first.

Further down on https://github.com/ojkelly/yarn.build/blob/trunk/packages/plugins/plugin-build/src/commands/build/index.ts#L157 we use the following line to add a target workspace

```
                await supervisor.addBuildTarget(matchingWorkspace);
```

---

Can you try building in the specific dir of the package you want, and confirm if it does or doesn't rebuild the other ones. that is, it only build the deps of the current directory. Because if that's the case, the solution mentioned above is probably doable.

**Comment by oliversalzburg** [comment]
> I think this is something you can do by running yarn.build in the specific directory you want.

I actually wasn't aware of this. I'll see if this will work for me. Thanks!

**Comment by oliversalzburg** [comment]
This is working perfectly. I just need to work on better VS Code integration

**Comment by oliversalzburg** [comment]
Not sure if you say this on the yarn Discord, but I made some progress with what I had in mind.

Being able to easily launch these targetted builds from VS Code before a debugging session, without having to duplicate all the launch configurations and tasks in my monorepo was the key motivator.

https://marketplace.visualstudio.com/items?itemName=OliverSalzburg.monolit
