### ISSUE TITLE
Unable to use exclude option with bundle

### ISSUE THREAD

**Issue by vhiairrassary** [ojkelly/yarn.build#87]
Thanks for this great plugin!

While I was able to bundle my code for AWS Lambda using this plugin, I wanted to exclude some files and directories (such as configuration files, sources - which use Typescript and are bundled/minified by webpack; etc.).

Having a look at the sources I found the undocumented `exclude` option:
https://github.com/ojkelly/yarn.build/blob/b0f35c7a5d47091a20ddb26dea805e591a0009e0/packages/plugins/plugin-build/src/commands/bundle/index.ts#L34-L35

Unfortunately I am not sure to understand how it works. After adding a couple of `console.log`:
```diff
diff --git a/packages/plugins/plugin-build/src/commands/bundle/index.ts b/packages/plugins/plugin-build/src/commands/bundle/index.ts
index 00a065d..570521a 100644
--- a/packages/plugins/plugin-build/src/commands/bundle/index.ts
+++ b/packages/plugins/plugin-build/src/commands/bundle/index.ts
@@ -106,22 +106,26 @@ export default class Bundler extends BaseCommand {

   async removeExcluded(tmpDir: PortablePath, excluded: PortablePath[]) {
     const gitDir = `${tmpDir}/.git` as PortablePath;

     try {
       if (await xfs.lstatPromise(gitDir)) {
         await xfs.removePromise(gitDir);
       }
     } catch (e) {}

     await excluded.map(async (p) => {
+      console.log('****');
+      console.log(p);
+      console.log(tmpDir);
+
       if (!p.startsWith(tmpDir)) {
         // Don't remove anything not in the tmp directory
         return;
       }

       if (await xfs.lstatPromise(p)) {
         await xfs.removePromise(p);
       }
     });
   }

```
and running `yarn bundle --exclude aaa --exclude bbb` we can see the following output:
```
****
aaa
/private/var/folders/3s/_2m5qbkj6czcwc8xsvwbg4n40000gn/T/xfs-d6e54876
****
bbb
/private/var/folders/3s/_2m5qbkj6czcwc8xsvwbg4n40000gn/T/xfs-d6e54876
****
/private/var/folders/3s/_2m5qbkj6czcwc8xsvwbg4n40000gn/T/xfs-d6e54876/packages/lambda-api/bundle.zip
/private/var/folders/3s/_2m5qbkj6czcwc8xsvwbg4n40000gn/T/xfs-d6e54876
```
The last trace is the output artefact excluded by default. But, as you can see, to use the `exclude` option you need to prefix each path by the tmp. directory - which does not exist yet at invocation time 😬

Here are my thoughts:
- I understand the `exclude` option is not yet public (not mentioned in CLI help text, README.md, config.js, etc.) and may not yet be ready for usage;
- The plugin could certainly prefixes all paths from `exclude` with the tmp. dir. (as it already does with the artefact);
- Given my usage, a `include` option may be better (I just want to ship `dist` directories);
- Currently `exclude` accepts a list of strings, we could also accept regex in `.yarnbuildrc.yml`.

I would love to get some feedbacks. And of course I am willing to create a PR if maintainers are interested 🚀

**Comment by ojkelly** [comment]
Hey 👋 

The intent was to look at `package.json#main` and use that folder for bundling.

https://github.com/ojkelly/yarn.build/blob/b0f35c7a5d47091a20ddb26dea805e591a0009e0/packages/plugins/plugin-build/src/commands/bundle/index.ts#L214

There has also been work done to enable per folder customisation for what you're talking about there. the `folderConfiguration` described in the readme.

The general approach to bundling here, is to copy the whole repo to a temporary directory, and then remove everything not needed. Then drop the `entrypoint.js` and zip it all up.

The main question just comes down to what's removed. So we remove anything the package we are bundling has not declared as a dependency.

Because the yarn 2+ setups use PnP, and possibly reference other local packages (ie in your repo, not on npm), we need to preserve the structure of the whole repo.

So bundle won't just bundle the `dist` folder. It bundles the whole workspace, with a file that starts whatever script you reference in `package.json#main`.

You should be able to set that to something like `"main": "dist/index.js"` and then run `node entrypoint.js` in your lambda or docker container.

---

Exclude is probably ready to pull up into public use. The questions around it have mainly been should it be configured per package, or globally. The answer seems to be per package.

It does sound like it would be useful to extend `exclude` a bit, to allow you to specify folders to remove for bundling as well.

**Comment by ojkelly** [comment]
I'm going to close this issue, but feel free to re-open or comment if you are still having trouble or have more information.
